source/Product/MOD4.Web/Controllers/AccessFabController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using MOD4.Web.DomainService;
using MOD4.Web.DomainService.Entity;
using MOD4.Web.Enum;
using Utility.Helper;
using MOD4.Web.Models;
using MOD4.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MOD4.Web.Controllers
{
    [Authorize]
    public class AccessFabController : BaseController
    {
        private readonly IAccessFabDomainService _accessFabDomainService;
        private readonly IOptionDomainService _optionDomainService;
        private readonly ILogger<HomeController> _logger;

        public AccessFabController(IHttpContextAccessor httpContextAccessor,
            IAccessFabDomainService accessFabDomainService,
            IOptionDomainService optionDomainService,
            IAccountDomainService accountDomainService,
            ILogger<HomeController> logger)
            : base(httpContextAccessor, accountDomainService)
        {
            _accessFabDomainService = accessFabDomainService;
            _logger = logger;
            _optionDomainService = optionDomainService;
        }

        /// <summary>
        /// 管制口 - 首頁
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            try
            {
                // 主頁搜尋下拉選項
                var _optionList = _optionDomainService.GetAccessFabOptions();

                // 訂單狀態
                ViewBag.StatusList = new SelectList(_optionList.FirstOrDefault(f => f.Item1 == "statusList").Item2, "Id", "Value");
                // 入廠性質
                ViewBag.FabInTypeList = new SelectList(_optionList.FirstOrDefault(f => f.Item1 == "fabInTypeList").Item2, "Id", "Value");
                // 入廠對象
                ViewBag.FabInCategoryList = new SelectList(_optionList.FirstOrDefault(f => f.Item1 == "fabInCategoryList").Item2, "Id", "Value");

                UserEntity _userInfo = GetUserInfo();
                // user 當前權限
                var _userCurrentPagePermission = _userInfo.UserMenuPermissionList.FirstOrDefault(f => f.MenuSn == MenuEnum.AccessFab);
                ViewBag.UserPermission = new UserPermissionViewModel
                {
                    AccountSn = _userCurrentPagePermission.AccountSn,
                    MenuSn = _userCurrentPagePermission.MenuSn,
                    AccountPermission = _userCurrentPagePermission.AccountPermission
                };

                List<AccessFabOrderEntity> _result = _accessFabDomainService.GetList(_userInfo, new AccessFabSelectOptionEntity());

                List<AccessFabMainViewModel> _resAccessList = _result.Select(s => new AccessFabMainViewModel
                {
                    OrderSn = s.OrderSn,
                    OrderNo = s.OrderNo,
                    Applicant = s.Applicant,
                    Date = s.CreateTimeStr,
                    FabInCategory = s.Category,
                    FabInType = s.FabInType,
                    Status = s.Status,
                    StatusId = s.StatusId,
                    AuditAccount = s.AuditAccountName,
                    Content = s.Content,
                    Url = s.Url
                }).ToList();

                return View(_resAccessList);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new ErrorViewModel { Message = ex.Message });
            }
        }

        [HttpGet]
        public IActionResult Search([FromQuery] string startDate, string endDate, int statusId, int fabInTypeId, string orderNo, string applicant)
        {
            try
            {
                var _userInfo = GetUserInfo();

                List<AccessFabOrderEntity> _result = _accessFabDomainService.GetList(_userInfo,
                    new AccessFabSelectOptionEntity
                    {
                        StartDate = startDate,
                        EndDate = endDate,
                        StatusId = statusId,
                        FabInTypeId = fabInTypeId,
                        OrderNo = orderNo,
                        Applicant = applicant
                    });

                List<AccessFabMainViewModel> _resAccessList = _result.Select(s => new AccessFabMainViewModel
                {
                    OrderSn = s.OrderSn,
                    OrderNo = s.OrderNo,
                    Applicant = s.Applicant,
                    Date = s.CreateTimeStr,
                    FabInCategory = s.Category,
                    FabInType = s.FabInType,
                    Status = s.Status,
                    StatusId = s.StatusId,
                    AuditAccount = s.AuditAccountName,
                    Content = s.Content,
                    Url = s.Url
                }).ToList();

                return PartialView("_PartialTable", _resAccessList);
            }
            catch (Exception ex)
            {
                return Json(new { Msg = ex.Message });
            }
        }

        [HttpGet]
        public IActionResult Edit([FromQuery] int orderSn)
        {
            try
            {
                var _optionList = _optionDomainService.GetAccessFabOptions();

                ViewBag.StatusList = new SelectList(_optionList.FirstOrDefault(f => f.Item1 == "statusList").Item2, "Id", "Value");
                ViewBag.FabInTypeList = new SelectList(_optionList.FirstOrDefault(f => f.Item1 == "fabInTypeList").Item2, "Id", "Value");
                ViewBag.FabInCategoryList = new SelectList(_optionList.FirstOrDefault(f => f.Item1 == "fabInCategoryList").Item2, "Id", "Value");
                ViewBag.AccountName = GetUserInfo().Name;

                AccessFabOrderEntity _accessFabOrderData = _accessFabDomainService.GetDetail(orderSn);

                var _res = new AccessFabDetailPageViewModel
                {
                    OrderSn = orderSn,
                    FabInTypeId = _accessFabOrderData.FabInTypeId,
                    FabInOtherType = _accessFabOrderData.FabInOtherType,
                    Applicant = _accessFabOrderData.Applicant,
                    ApplicantMVPN = _accessFabOrderData.ApplicantMVPN,
                    FabInCategoryId = _accessFabOrderData.CategoryId,
                    FillOutPerson = _accessFabOrderData.FillOutPerson,
                    AccompanyingPerson = _accessFabOrderData.AccompanyingPerson,
                    AccompanyingPersonMVPN = _accessFabOrderData.AccompanyingPersonMVPN,
                    Content = _accessFabOrderData.Content,
                    Route = _accessFabOrderData.Route,
                    JobId = _accessFabOrderData.JobId,
                    AccessFabOrderNo = _accessFabOrderData.OrderNo,
                    OrderStatus = _accessFabOrderData.StatusId.GetDescription(),
                    FabInDate = _accessFabOrderData.FabInDate,
                    FabOutDate = _accessFabOrderData.FabOutDate,
                    CreateTimeStr = _accessFabOrderData.CreateTime.ToString("yyyy-MM-dd HH:mm:ss"),
                    AccessPersonList = _accessFabOrderData.DetailList.Select(detail => new AccessFabPersonsViewModel
                    {
                        DetailSn = detail.Sn,
                        CompanyName = detail.CompanyName,
                        Name = detail.Name,
                        GuestPhone = detail.GuestPhone,
                        ClotheSize = detail.ClotheSize,
                        ShoesSize = detail.ShoesSize
                    }).ToList(),
                    AuditHistory = _accessFabOrderData.AuditFlow.Select(his => new AccessFabAuditHistoryViewModel
                    {
                        AuditSn = his.AuditSn,
                        AuditAccountName = his.AuditAccountName,
                        StatusId = his.StatusId,
                        Status = his.StatusId.GetDescription(),
                        ReceivedTimeStr = his.ReceivedTimeStr,
                        AuditTimeStr = his.AuditTimeStr,
                        AuditRemark = his.AuditRemark,
                        Duration = his.Duration
                    }).ToList()
                };

                return View(_res);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home", new ErrorViewModel { Message = ex.Message });
            }
        }

        [HttpPost]
        public IActionResult Edit([FromForm] AccessFabDetailPageViewModel accessFabOrderEditModel)
        {
            try
            {
                string _editRes = _accessFabDomainService.Edit(new AccessFabOrderEntity
                {
                    OrderSn = accessFabOrderEditModel.OrderSn,
                    FabInTypeId = accessFabOrderEditModel.FabInTypeId,
                    FabInOtherType = accessFabOrderEditModel.FabInOtherType,
                    FillOutPerson = accessFabOrderEditModel.FillOutPerson,
                    Applicant = accessFabOrderEditModel.Applicant,
                    ApplicantMVPN = accessFabOrderEditModel.ApplicantMVPN,
                    CategoryId = accessFabOrderEditModel.FabInCategoryId,
                    AccompanyingPerson = accessFabOrderEditModel.AccompanyingPerson,
                    AccompanyingPersonMVPN = accessFabOrderEditModel.AccompanyingPersonMVPN,
                    Content = accessFabOrderEditModel.Content,
                    Route = accessFabOrderEditModel.Route,
                    JobId = accessFabOrderEditModel.JobId,
                    FabInDate = accessFabOrderEditModel.FabInDate,
                    FabOutDate = accessFabOrderEditModel.FabOutDate,
                    DetailList = accessFabOrderEditModel.AccessPersonList.Select(detail => new AccessFabOrderDetailEntity
                    {
                        Sn = detail.DetailSn,
                        CompanyName = detail.CompanyName,

source/Product/MOD4.Web/Views/AccessFab/Audit.cshtml
@model List<MOD4.Web.ViewModel.AccessFabMainViewModel>

@{
    ViewBag.Title = "個人簽核單";
}

<style>
    .card-title {
        font-size: 30px;
        font-weight: 900;
    }

    table {
        box-shadow: 2px 2px 2px #999;
    }

    .card {
        box-shadow: 2px 2px 2px #999;
        background-color: #c3cadb;
    }

    .my-control {
        display: initial;
        width: 60%;
        height: calc(2.25rem + 2px);
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        box-shadow: inset 0 0 0 transparent;
        transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    }
</style>


<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">進出申請單 簽核作業</h3>
                        </div>
                        <div class="card-body">
                            <span style="color:red;font-size:8px">*預設顯示30天入廠申請單</span>
                            <fieldset id="searchArea">
                                <legend id="legend">查詢區塊</legend>
                                <div class="row" style="margin-bottom:5px">
                                    <div class="col-3">
                                        <label>入廠起日：</label>
                                        <input id="startDTE" class="my-control" type="date" name="name" value="" />
                                    </div>
                                    <div class="col-3">
                                        <label>入廠訖日：</label>
                                        <input id="endDTE" class="my-control" type="date" name="name" value="" />
                                    </div>
                                    <div class="col-3">
                                        <label>入廠性質：</label>
                                        <select id="selFabInType" class="custom-select" style="width:50%" asp-items="@(SelectList)ViewBag.FabInTypeList">
                                            <option value="0"></option>
                                        </select>
                                    </div>
                                    <div class="col-3">
                                        <label>入廠人員：</label>
                                        <input id="guestName" type="text" class="form-control" style="width:65%;display:initial;" />
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-3">
                                        <label>申請人：</label>
                                        <input id="applicant" type="text" class="form-control" style="width:65%;display:initial;" />
                                    </div>
                                    <div>
                                        <input id="btnSearch" type="button" class="btn btn-info" style="float: right" name="name" value="查詢" />
                                    </div>
                                </div>
                                <br />
                            </fieldset>
                            <br id="diviBr" />

                            <partial name="_PartialTable" model="Model" />
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="detailModalLabel" aria-hidden="true">
                    </div>
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>


@section scripts {
    <script type="text/javascript">

        let myFun = {
            mainSearch() {
                $.ajax({
                    url: "./Audit/Search?startFabInDate=" + $("#startDTE").val() + "&endFabInDate=" + $("#endDTE").val() + "&fabInTypeId=" + $("#selFabInType").val() + "&guestName=" + $("#guestName").val() + "&applicant=" + $("#applicant").val(),
                    type: "GET",
                    dataType: "html",
                    success: function (res) {
                        if (isJsonString(res)) {
                            var _res = JSON.parse(res);
                            if (result == '""') {
                                alert('查無資料');
                            }
                            if ('isException' in _res) {
                                alert(_res.msg);
                                return false;
                            }
                        }
                        else {
                            $("#table1_wrapper").remove();
                            $("#diviBr").after(res);

                            $('th:nth-child(6)').hide();
                            $('td:nth-child(6)').hide();

                            $('#table1').DataTable({
                                "responsive": false,
                                "lengthChange": true,
                                "autoWidth": false,
                                "paging": true,
                                "order": [[1, "desc"]]
                            }).buttons().container().appendTo('#table1_wrapper .col-md-6:eq(0)');
                        }
                    }
                });
            },
            verifyToDetail(url, sn) {
                $.ajax({
                    url: "./Audit/Verify/" + sn,
                    type: "GET",
                    dataType: "html",
                    success: function (res) {
                        var _res = JSON.parse(res);
                        if (_res.isSuccess) {
                            location.href = url;
                        }
                        else {
                            alert(_res.msg);
                            location.reload();
                        }
                    }
                });
            }
        }

        $(function () {

            $('th:nth-child(6)').hide();
            $('td:nth-child(6)').hide();

            $('#table1').DataTable({
                "paging": true,
                //"searching": false,
                //"ordering": true,
                //"info": true,
                "responsive": false,
                "lengthChange": true,
                "autoWidth": false,
                "order": [[1, "desc"]],
                /*"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]*/
            }).buttons().container().appendTo('#table1_wrapper .col-md-6:eq(0)');

            $("#dropCat,#dropStatus").multiselect({});

            $('#startDTE').attr("max", new Date().toISOString().slice(0, 10));
            $('#endDTE').attr("max", new Date().toISOString().slice(0, 10));
        });

        $("#btnSearch").click(myFun.mainSearch);

        function orderNoClick(url, sn) {
            myFun.verifyToDetail(url, sn);
        }

    </script>
}

source/Product/MOD4.Web/Views/AccessFab/AuditDetail.cshtml
@model MOD4.Web.ViewModel.AccessFabDetailPageViewModel
@using MOD4.Web.ViewModel

@{
    ViewBag.Title = "申請單簽核";
}


<style>
    /*.card {
        box-shadow: 1px 2px 2px 2px #999;
        margin-top: 5px;
    }

    .card-header, .card-body, .card-footer {
        background-color: #c3cadb;
    }

    .card-title {
        font-family: "Microsoft JhengHei";
        font-weight: 900;
        font-style: italic;
        font-size: 30px;
    }*/

    label[name="underline"] {
        text-decoration: underline;
    }

    div[name="historyLine"] {
        display: flex;
    }
</style>

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">申 請 單 簽 核</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <form id="detailForm">
                            <div class="card-body">
                                <partial name="_PartialDetailForm" model="Model" />
                                @{
                                    UserPermissionViewModel _test = (UserPermissionViewModel)ViewBag.UserPermission;

                                    if (Convert.ToBoolean(_test.AccountPermission & (int)MOD4.Web.Enum.PermissionEnum.Audit))
                                    {
                                        <div>
                                            <input class="btn btn-success" type="button" data-toggle="modal" data-target="#modal-approve" value="核准" />

                                            <input class="btn btn-danger" type="button" data-toggle="modal" data-target="#modal-reject" value="剔退" />
                                        </div>
                                    }
                                }
                            </div>
                        </form>
                        <div class="modal fade" id="modal-approve">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header" style="padding: 5px">
                                        <p>確認核准?</p>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div>
                                            <label class="col-form-label" asp-for="Remark"></label>
                                        </div>
                                        <div>
                                            <textarea id="approveRemark" cols="30" rows="5"></textarea>
                                        </div>
                                    </div>
                                    <div class="modal-footer justify-content-between">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">否</button>
                                        <input type="button" class="btn btn-success" value="確認" onclick="updateApprove()" />
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                        </div>
                        <div class="modal fade" id="modal-reject">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header" style="padding: 5px">
                                        <p>確認剔退?</p>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div>
                                            <label class="col-form-label" asp-for="Remark"></label>
                                        </div>
                                        <div>
                                            <textarea id="rejectRemark" cols="30" rows="5"></textarea>
                                        </div>
                                    </div>
                                    <div class="modal-footer justify-content-between">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">否</button>
                                        <input type="button" class="btn btn-danger" value="確認" onclick="updateReject()" />
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@section scripts{
    <script type="text/javascript">

        function updateApprove() {

            let _requestModel = {};
            _requestModel['OrderSn'] = $("#OrderSn").val();
            _requestModel['OrderStatusId'] = 5;
            _requestModel['Remark'] = $("#approveRemark").val();

            //e.preventDefault();
            $.blockUI({
                message: '請稍等...',
                css: {
                    border: 'none',
                    padding: '5px',
                    backgroundColor: '#000',
                    '-webkit-border-radius': '10px',
                    '-moz-border-radius': '10px',
                    opacity: '.5',
                    color: '#fff',
                    fontSize: '25px',
                    fontFamily: '微軟正黑體',
                    fontWeight: 300,
                }
            });
            $.ajax({
                url: "../Update",
                type: "POST",
                data: { 'approveViewModel': _requestModel },
                success: function (res) {
                    $.unblockUI();
                    if (res.isSuccess) {
                        alert('已核准');
                        location.href = "@Url.ActionLink("Audit", "AccessFab")";
                    }
                    else {
                        alert(res.msg);
                        return false;
                    }
                }
            });
        }

        function updateReject() {

            let _requestModel = {};
            _requestModel['OrderSn'] = $("#OrderSn").val();
            _requestModel['OrderStatusId'] = 2;
            _requestModel['Remark'] = $("#rejectRemark").val();

            //e.preventDefault();
            $.blockUI({
                message: '請稍等...',
                css: {
                    border: 'none',
                    padding: '5px',
                    backgroundColor: '#000',
                    '-webkit-border-radius': '10px',
                    '-moz-border-radius': '10px',
                    opacity: '.5',
                    color: '#fff',
                    fontSize: '25px',
                    fontFamily: '微軟正黑體',
                    fontWeight: 300,
                }
            });
            $.ajax({
                url: "../Update",
                type: "POST",
                data: { 'approveViewModel': _requestModel },
                success: function (res) {
                    $.unblockUI();
                    if (res.isSuccess) {
                        alert('剔退成功');
                        location.href = "@Url.ActionLink("Audit", "AccessFab")";
                    }
                    else {
                        alert(res.msg);
                        return false;
                    }
                }
            });
        }

    </script>
}

source/Product/MOD4.Web/Views/AccessFab/Detail.cshtml
@model MOD4.Web.ViewModel.AccessFabDetailPageViewModel

@{
    ViewBag.Title = "進出申請單明細";
}


<style>
    /*.card {
        box-shadow: 1px 2px 2px 2px #999;
        margin-top: 5px;
    }

    .card-header, .card-body, .card-footer {
        background-color: #c3cadb;
    }

    .card-title {
        font-family: "Microsoft JhengHei";
        font-weight: 900;
        font-style: italic;
        font-size: 30px;
    }*/

    label[name="underline"] {
        text-decoration: underline;
    }

    div[name="historyLine"] {
        display: flex;
    }
</style>

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">申 請 單 明 細</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form>
                            <div class="card-body">
                                <partial name="_PartialDetailForm" model="Model" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

source/Product/MOD4.Web/Views/AccessFab/_PartialTable.cshtml
@model List<MOD4.Web.ViewModel.AccessFabMainViewModel>

<table id="table1" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.First().OrderNo)</th>
            <th>@Html.DisplayNameFor(model => model.First().FabInDate)</th>
            <th>@Html.DisplayNameFor(model => model.First().FabInCategory)</th>
            @*<th>@Html.DisplayNameFor(model => model.First().FabInType)</th>*@
            <th>@Html.DisplayNameFor(model => model.First().Content)</th>
            <th>@Html.DisplayNameFor(model => model.First().GustNames)</th>
            <th>@Html.DisplayNameFor(model => model.First().AuditAccount)</th>
            <th>@Html.DisplayNameFor(model => model.First().Date)</th>
            <th>@Html.DisplayNameFor(model => model.First().Applicant)</th>
            <th>@Html.DisplayNameFor(model => model.First().Status)</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var order in Model)
            {
                string _color = "";
                if (order.StatusId == MOD4.Web.Enum.AuditStatusEnum.Rejected)
                    _color = "#e69a9a";

                <tr style="background-color: @_color ">
                    <td style="width:7%"><a href="#" onclick="orderNoClick('@order.Url',@order.OrderSn)">@order.OrderNo</a></td>
                    <td style="width:7%;font-weight:600">@order.FabInDate</td>
                    <td style="width:7%">@order.FabInCategory</td>
                    @*<td style="width:9%">@order.FabInType</td>*@
                    <td style="width:12%">@order.Content</td>
                    <td style="width:15%">@order.GustNames</td>
                    <td style="width:8%">@order.AuditAccount</td>
                    <td style="width:7%;font-weight:600">@order.Date</td>
                    <td style="width:7%">@order.Applicant</td>
                    <td style="width:6%">@order.Status</td>
                </tr>
            }
        }
    </tbody>
</table>